// bin2h quickly hacked together by kb because I couldn't find one with the proper license :)
// Usage: bin2h <file>
// Generates <file>.h with an array called "data"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv)
{
  if (argc < 2)
  {
    printf("not enough arguments\n");
    return 1;
  }

  FILE *infile, *outfile;
  
  if (fopen_s(&infile, argv[1], "rb"))
  {
    printf("file not found\n");
    return 3;
  }

  char outname[1024];
  strcpy_s(outname, argv[1]);
  strcat_s(outname, ".h");
  fopen_s(&outfile, outname, "w");

  fprintf_s(outfile, "// generated by bin2h, don't edit\n");
  fprintf_s(outfile, "#pragma once\n\n");

  fprintf_s(outfile, "static const unsigned char data[] = {\n");
  size_t read;
  do
  {
    unsigned char data[16];
    read = fread(data, 1, 16, infile);
    fprintf_s(outfile, "  ");
    for (size_t i = 0; i < read; i++)
      fprintf(outfile, "0x%02x, ", data[i]);
    fprintf_s(outfile, "\n");
  } while (read == 16);
  fprintf_s(outfile, "};");

  fclose(outfile);
  fclose(infile);
  return 0;
}
